### ISSUE TITLE
fold_sum_1, fold_mul_1 need init value for null parameter case

### ISSUE THREAD

**Issue by richardebel** [wichtounet/articles#13]
fold_expressions.cpp wont compile with gcc9.2 or MSVC16.
an initial value is needed for + and * operation.

this compiles and works:
template <typename... T>
auto fold_sum_1(T... s)
{
    return (s + ... + 0);
}

template <typename... T>
auto fold_mul_1(T... s)
{
    return (s * ... * 1);
}

**Comment by wichtounet** [comment]
Hi Richard, 

I am almost sure this would work with GCC 9.2 as long as you use -std=c++17. 
As for MSVC, I would indeed not be surprised if this didn't work. 

Since this example is supposed to show the two possibilities of the C++17 standard (with and without init parameter), I am not going to update it. This is perfectly fine according to the standard.
I am not using MSVC and I am almost sure a lot of this code in this repository would not compile with it.

Thanks for letting me know!
